### ISSUE TITLE
关于opcode的优化

### ISSUE THREAD

**Issue by jhdxr** [reeze/tipi#62]
看完 《第七章 Zend虚拟机 » 第四节 PHP代码的加密解密》我有个疑问，因为php code到opcode是一个直译的过程，并没有任何优化（别的语言的编译器一般会做一些优化，比如去除无用变量之类的），那么是否可以在扩展这一层面上做一些这样子的工作呢？或者说现在是否有一些扩展已经这么做了？求指教，多谢。

**Comment by reeze** [comment]
是的 @Gasol 已经回答了 :)
